CREATE SCHEMA IF NOT EXISTS SENTINEL;

OPEN SCHEMA SENTINEL;

CREATE TABLE IF NOT EXISTS ATTACK_FINGERPRINTS (
    ID            INTEGER IDENTITY PRIMARY KEY,
    CATEGORY      VARCHAR(100),
    PATTERN_TEXT  VARCHAR(2000),
    EMBEDDING     VARCHAR(20000)  -- JSON-encoded float array, parsed in Python
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID                INTEGER IDENTITY PRIMARY KEY,
    SESSION_ID        VARCHAR(100),
    TS                TIMESTAMP,
    PROMPT            VARCHAR(4000),
    RESPONSE          VARCHAR(4000),
    HEURISTIC_SCORE   DECIMAL(5,4),
    SIMILARITY_SCORE  DECIMAL(5,4),
    MATCHED_CATEGORY  VARCHAR(100),
    DECISION          VARCHAR(20),
    LATENCY_MS         INTEGER
);
